# Generated by Django 5.2 on 2025-04-23 09:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientDetails',
            new_name='ClientDetails',
        ),
    ]
