# Generated by Django 5.2 on 2025-04-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_lawyerdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyerdetails',
            name='category',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
