# Generated by Django 5.2 on 2025-04-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_remove_appointment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_mode',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('lawyer', 'appointment_date', 'appointment_time')},
        ),
    ]
