# Generated by Django 5.2 on 2025-04-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_vaultfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('Paid', 'Paid'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
