# Generated by Django 5.2 on 2025-04-30 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyerdetails',
            name='license_number',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
