# Generated by Django 5.2 on 2025-04-30 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_lawyerdetails_license_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyerdetails',
            name='license_number',
            field=models.CharField(max_length=20),
        ),
    ]
