# Generated by Django 5.2 on 2025-04-30 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_alter_lawyerdetails_license_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyerdetails',
            name='license_number',
        ),
    ]
