# Generated by Django 5.2 on 2025-04-30 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_remove_lawyerdetails_license_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyerdetails',
            name='license_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
