# Generated by Django 5.2 on 2025-04-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_lawyerdetails_license_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyerdetails',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
