# Generated by Django 5.2 on 2025-05-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_lawyerdetails_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='case_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('won', 'Won'), ('lost', 'Lost'), ('in_progress', 'In Progress'), ('in_progress_10', 'In Progress (10%)'), ('in_progress_30', 'In Progress (30%)'), ('in_progress_50', 'In Progress (50%)'), ('in_progress_80', 'In Progress (80%)')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
