# Generated by Django 5.2 on 2025-05-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='case_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('won', 'Won'), ('lost', 'Lost'), ('in progress 10%', 'In Progress (10%)'), ('in progress 30%', 'In Progress (30%)'), ('in progress 50%', 'In Progress (50%)'), ('in progress 80%', 'In Progress (80%)')], default='pending', max_length=20),
        ),
    ]
